#!/usr/bin/env python3
"""Merge Ghidra's functions.json + symbols.json into a names file the
gb-recompiled recompiler consumes via --names.

Output format is one entry per line, matching the recompiler's bank:addr
convention:

    <bank>:<hexaddr> <c_identifier>

e.g.   3:4d23 AdvanceLogoState

Ghidra placeholder names (FUN_/SUB_/LAB_/DAT_/…) are dropped — only
meaningful names (user- or analysis-assigned symbols, non-auto function
names) are emitted, so unnamed functions keep the recompiler's default
func_<bank>_<addr>. decompiled.json is not required here (it's for human
reference), but is read if present to fill in a name from a function whose
symbol was missed.
"""
import argparse
import json
import os
import re
import sys

C_KEYWORDS = set((
    "auto break case char const continue default do double else enum extern "
    "float for goto if inline int long register restrict return short signed "
    "sizeof static struct switch typedef union unsigned void volatile while "
    "bool true false"
).split())


def sanitize(name):
    """Turn a Ghidra symbol name into a safe C identifier."""
    name = name.split("::")[-1]            # drop namespace qualifiers
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not name:
        name = "fn"
    if name[0].isdigit():
        name = "_" + name
    if name in C_KEYWORDS:
        name = name + "_"
    return name


def load(path):
    if not os.path.isfile(path):
        return []
    with open(path, encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            sys.exit("error: %s is not valid JSON (%s)" % (path, e))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("indir", help="directory containing functions.json / symbols.json")
    ap.add_argument("-o", "--out", default="names.sym", help="output names file")
    args = ap.parse_args()

    funcs = load(os.path.join(args.indir, "functions.json"))
    syms = load(os.path.join(args.indir, "symbols.json"))

    # (bank, addr) -> (name, priority). Higher priority wins.
    best = {}

    def consider(bank, addr_hex, name, priority):
        addr = int(addr_hex, 16) if isinstance(addr_hex, str) else int(addr_hex)
        key = (int(bank), addr)
        cur = best.get(key)
        if cur is None or priority > cur[1]:
            best[key] = (name, priority)

    # symbols.json is already filtered to meaningful names by the exporter.
    for s in syms:
        consider(s["bank"], s["addr"], s["name"], 2)
    # named functions (skip Ghidra auto-names).
    for f in funcs:
        if not f.get("auto", False):
            consider(f["bank"], f["addr"], f["name"], 1)

    # Sanitize + de-duplicate identifiers.
    used = {}
    rows = []
    for (bank, addr), (name, _prio) in sorted(best.items()):
        ident = sanitize(name)
        if ident in used and used[ident] != (bank, addr):
            suffix = ("_%x_%04x" % (bank, addr)) if bank else ("_%04x" % addr)
            ident = ident + suffix
        used[ident] = (bank, addr)
        rows.append((bank, addr, ident))

    with open(args.out, "w", encoding="utf-8") as w:
        w.write("# Generated by build_names.py — bank:addr c_identifier\n")
        for bank, addr, ident in rows:
            w.write("%d:%04x %s\n" % (bank, addr, ident))

    print("[build_names] %d names -> %s (from %d functions, %d symbols)"
          % (len(rows), args.out, len(funcs), len(syms)))


if __name__ == "__main__":
    main()
